// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_XPeHS3quBxP35JOaILBLODzuEqZYek',
    appId: '1:908460332354:web:7979a979db530a9d0524db',
    messagingSenderId: '908460332354',
    projectId: 'cantina---senai',
    authDomain: 'cantina---senai.firebaseapp.com',
    databaseURL: 'https://cantina---senai-default-rtdb.firebaseio.com',
    storageBucket: 'cantina---senai.appspot.com',
    measurementId: 'G-WEZQZMTV72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xIKuhnJiSKHG8Hdga4XGlIzRlCoTABA',
    appId: '1:908460332354:android:67a801223504de8b0524db',
    messagingSenderId: '908460332354',
    projectId: 'cantina---senai',
    databaseURL: 'https://cantina---senai-default-rtdb.firebaseio.com',
    storageBucket: 'cantina---senai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUSbvcK2hH1Vfn27oxHsbuTQnfhwBfwQ',
    appId: '1:908460332354:ios:2ef33441223309f80524db',
    messagingSenderId: '908460332354',
    projectId: 'cantina---senai',
    databaseURL: 'https://cantina---senai-default-rtdb.firebaseio.com',
    storageBucket: 'cantina---senai.appspot.com',
    iosBundleId: 'com.example.cantinaSenai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKUSbvcK2hH1Vfn27oxHsbuTQnfhwBfwQ',
    appId: '1:908460332354:ios:2ef33441223309f80524db',
    messagingSenderId: '908460332354',
    projectId: 'cantina---senai',
    databaseURL: 'https://cantina---senai-default-rtdb.firebaseio.com',
    storageBucket: 'cantina---senai.appspot.com',
    iosBundleId: 'com.example.cantinaSenai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_XPeHS3quBxP35JOaILBLODzuEqZYek',
    appId: '1:908460332354:web:fb44b08616493fb30524db',
    messagingSenderId: '908460332354',
    projectId: 'cantina---senai',
    authDomain: 'cantina---senai.firebaseapp.com',
    databaseURL: 'https://cantina---senai-default-rtdb.firebaseio.com',
    storageBucket: 'cantina---senai.appspot.com',
    measurementId: 'G-MLJX9F7DZX',
  );
}
